- name: Compile dmenu
  ansible.builtin.command:
    cmd: make
    creates: /usr/local/bin/dmenu
  args:
    chdir: "{{ ansible_env.HOME }}/git/dotfiles/bin/suckless/dmenu-5.2/"

- name: Install dmenu
  ansible.builtin.command:
    cmd: make install
    creates: /usr/local/bin/dmenu
  args:
    chdir: "{{ ansible_env.HOME }}/git/dotfiles/bin/suckless/dmenu-5.2/"
  become: yes
