- name: Compile st
  ansible.builtin.command:
    cmd: make
    creates: /usr/local/bin/st
  args:
    chdir: "{{ ansible_env.HOME }}/git/dotfiles/bin/suckless/st-0.9/"

- name: Install st
  ansible.builtin.command:
    cmd: make install
    creates: /usr/local/bin/st
  args:
    chdir: "{{ ansible_env.HOME }}/git/dotfiles/bin/suckless/st-0.9/"
  become: yes
