[manager]
sort_dir_first = true

[opener]
edit = [ { run = 'nvim "$@"', block = true }, ]
img = [ { run = 'feh "$@"', desc = "View image" }, ]
pdf = [ { run = 'zathura "$@"', desc = "Open pdf" }, ]

[open]
rules = [
  { mime = "text/*", use = "edit" },
	{ mime = "image/*", use = "img" },
	{ mime = "application/pdf", use = "pdf" },
]
